### ISSUE TITLE
Use fonts instead of background images

### ISSUE THREAD

**Issue by Paul-Browne** [kkuchta/css-only-chat#12]
So instead of requesting a bg image, you would use @fontface 

I think you can also use font subsetting to request fonts for certain characters

**Comment by myfonj** [comment]
Yes, it is [possible](https://github.com/jbtronics/CrookedStyleSheets/issues/24), but this approach alone could monitor only new unique characters, subsequent characters does not produce requests.  I [proposed](https://twitter.com/myfonj/status/1126441751126921216) perhaps it could be worked around if subsequent CSS updates defining new font stack for input involving one font covering known input value in single ligature and as a fallback classical "keylogging" font.

```CSS
@font-face { name: written; url(real font with single ligature of last known value)}
@font-face { name: logger; url(?key logging route); unicode-range: ... } /* etc etc */
input { font-family: written, logger; }
```
(all fonts names unique per response)

Obviously if this simple approach works, it could work just for typing, not deleting, pasting, moving cursor and typing in the middle etc.

---
Related https://github.com/kkuchta/css-only-chat/issues/2#issuecomment-491011541, https://github.com/kkuchta/css-only-chat/issues/11
